server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: classpath:application-db.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 407036214845-ueeq14iv6jlrll2agvjo80u1d28ueip3.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
          naver:
            client-id: gQw5Rk42qGsziiQ02E_c
            client-secret: QAFAOmPd8o
            authorization-grant-type: authorization_code
            client-name: naver
            redirect-uri: https://i9b309.p.ssafy.io/login/oauth2/code/kakao
            scope: profile,email
          kakao:
            client-id: 44008d7652c5441a5565af7920c090ff
            client-secret: EuQ0rlqxPY6wz6SitJEB5Q6fuvfds4i2
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: kakao
            redirect-uri: https://i9b309.p.ssafy.io/login/oauth2/code/kakao
            scope: openid, profile_nickname, account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id
  mvc:
    static-path-pattern: /static/**

auth:
  secretKey: PEIKPECKPEIKPECK
  redirectUrl: http://localhost:3000/userinfo
  ignored-urls: /login, /member/test, /member/signup, /member/login, /member/emoji,
    /member/prefix, /member/world, /member/taste, /member/signup/info